# Error handling with Promises

- When a promise is rejected, it `throws` an exception (Error instance).
- Or within the then block, if an error is encountered, execution will stop and program terminates.
- We can use the `catch` block to handle this error.
- In a promise chain, `catch` block handles errors for all the promises written above it.
