# Finally

- We have a task, and we do not care about whether the task complets or fails. We want to execute some code anyways.
- Finally can be used with try catch and promise chaining.
- We want to run some piece of code regardless of whether promise fulfils or rejects.
- Finally runs after the promise has settled(either fulfiled or rejected).

``` javascript
async function asyncTask() {
  try {
    const response = await fetch("https://jsonplaceholder.typicode.com/posts");
    const data = await response.json();
    console.log("TRY::");
  } catch (err) {
    console.log("CATCH::");
  } finally {
    console.log("FINALLY::");
  }
}

asyncTask();
```

``` javascript
fetch("https://jsonplaceholder.typicode.com/posts")
  .then((response) => response.json())
  .then((data) => console.log(data))
  .catch((err) => console.log(error))
  .finally(() => {
    stopLoading();
  });

```
